### ISSUE TITLE
Boxing Day

### ISSUE THREAD

**Issue by Malivil** [Malivil/TTT-Randomat-20-Jingle-Jam-2021#1]
- Suggested by: Fyxen
- Description: Boxing gloves for everyone!
-----
### Event Specifics
All players are given a custom boxing gloves melee weapon that:
- Does damage on normal punch
- Causes players to ragdoll on charge-up punch 
  - Ragdolled players can still take damage
-----
### Tasks
- [x] Create event
- [x] ConVars
  - [x] Punch damage (default to 5-10?)
- [x] Condition: Medium exists (for particle)
- [x] Create boxing gloves
  - [x] Copy model/animations/texture from Boxer role
  - [x] Weapon code
