### ISSUE TITLE
Jingle Jam 2021

### ISSUE THREAD

**Issue by Malivil** [Malivil/TTT-Randomat-20-Jingle-Jam-2021#3]
- Suggested by: Malivil
- Description: Weapons randomly jam
-----
### Event Specifics
All players have their weapons jam randomly

-----
### Tasks
- [x] Create event
- [x] ConVars
  - [x] Jam chance (the percent chance for a given player to have their weapon jammed each interval)
  - [x] Jam interval (seconds)
  - [x] Jam length (seconds)
